spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://192.168.71.1:5432/databaseName?useSSL=false

mybatis:
  type-aliases-package: com.cug.prototype.entity
  mapper-locations: classpath:mapper/*.xml
